### PR TITLE
Upgrade to Handlebars v1.3

### PR DESCRIPTION
**Pull request by cvburgess**

### CODE REVIEW

**Comment by cvburgess** [comment]
Version 1.3 adds some really nice features like subexpressions. I've been using 1.3 with the jQuery plugin for a few days now and haven't run into any issues.

**Comment by angelxmoreno** [comment]
i am currently using this with ver 1.3.0 by simply including that lib instead of the one that comes inside this plugin. what else would you need to change in the plugin to make it work? it seems to work just fine the way i am using it.

**Comment by shamasis** [comment]
I agree to @angelxmoreno. The handlebars library provided in this package is not mandatory to be used. If you have handlebars already included in your page, this would use that instead of the packaged one.

**Comment by cvburgess** [comment]
Can you include the plugin by itself then? Right now when you pull it in with bower you get the minified, combined library

**Comment by shamasis** [comment]
@cvburgess meanwhile you can point to `/src/plugin.js` and it would work provided you have handlebars included before that.

**Pull request closed without merging**
